# Generated by Django 4.2.20 on 2025-05-01 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=15, unique=True)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location_in_workshop', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('working_area', models.CharField(blank=True, max_length=100)),
                ('power_requirements', models.CharField(blank=True, max_length=100)),
                ('maximum_work_speed', models.CharField(blank=True, max_length=50)),
                ('precision', models.CharField(blank=True, max_length=50)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('setup_time', models.IntegerField(blank=True, null=True)),
                ('setup_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cleanup_time', models.IntegerField(blank=True, null=True)),
                ('cleanup_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('out_of_order', 'Out of Order')], default='active', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/machines/')),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(max_length=15, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special_skills', models.TextField(blank=True)),
                ('productivity_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('certified_machines', models.ManyToManyField(blank=True, related_name='certified_operators', to='workshop_app.machine')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_types', to='workshop_app.materialcategory')),
            ],
            options={
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('unit_of_measurement', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(blank=True, max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_stock_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_stock_alert', models.BooleanField(default=False)),
                ('location_in_workshop', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('project_association', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/materials/')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workshop_app.materialtype')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='workshop_app.machinetype'),
        ),
    ]
