# Generated by Django 4.2.20 on 2025-05-01 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='serial_number',
            field=models.CharField(blank=True, help_text="Manufacturer's serial number if applicable", max_length=50),
        ),
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text="Amount added in material's unit of measurement", max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Purchase price for this entry', max_digits=10)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('receipt', models.FileField(blank=True, help_text='PDF receipt for this purchase', null=True, upload_to='receipts/materials/')),
                ('supplier_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workshop_app.material')),
            ],
            options={
                'verbose_name_plural': 'Material Entries',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
    ]
