# Generated by Django 4.2.20 on 2025-05-01 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0003_materialtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('setup_time', models.IntegerField(default=0, help_text='Setup time in minutes')),
                ('cleanup_time', models.IntegerField(default=0, help_text='Cleanup time in minutes')),
                ('job_reference', models.CharField(blank=True, help_text='Reference to the job', max_length=100)),
                ('operator_name', models.CharField(blank=True, help_text='Name of the machine operator', max_length=100)),
                ('operation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('setup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cleanup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='workshop_app.machine')),
            ],
            options={
                'verbose_name_plural': 'Machine Usage Records',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MachineMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('inspection', 'Inspection'), ('calibration', 'Calibration'), ('other', 'Other')], max_length=20)),
                ('performed_by', models.CharField(help_text='Person or company who performed maintenance', max_length=100)),
                ('is_external_provider', models.BooleanField(default=False, help_text='Was maintenance done by external provider?')),
                ('tasks_performed', models.TextField(help_text='Description of maintenance tasks performed')),
                ('parts_replaced', models.TextField(blank=True, help_text='List of parts replaced during maintenance')),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Machine downtime in hours', max_digits=6, null=True)),
                ('result', models.TextField(blank=True, help_text='Result of the maintenance')),
                ('issues_found', models.TextField(blank=True, help_text='Issues discovered during maintenance')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/maintenance/')),
                ('documentation', models.FileField(blank=True, null=True, upload_to='docs/maintenance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='workshop_app.machine')),
            ],
            options={
                'verbose_name_plural': 'Machine Maintenance Records',
                'ordering': ['-maintenance_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the consumable part', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('part_number', models.CharField(blank=True, help_text="Manufacturer's part number", max_length=50)),
                ('current_stock', models.IntegerField(default=0)),
                ('minimum_stock_level', models.IntegerField(default=1)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expected_lifetime_hours', models.IntegerField(blank=True, help_text='Expected lifetime in machine operation hours', null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this consumable has been replaced')),
                ('supplier_name', models.CharField(blank=True, max_length=100)),
                ('supplier_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='workshop_app.machine')),
            ],
            options={
                'ordering': ['machine', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('machine_hours', models.IntegerField(blank=True, help_text='Machine hours at time of replacement', null=True)),
                ('replaced_by', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='workshop_app.machineconsumable')),
            ],
        ),
    ]
