# Generated by Django 4.2.20 on 2025-05-01 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_app', '0004_machineusage_machinemaintenance_machineconsumable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier_sku',
            field=models.CharField(blank=True, help_text="Supplier's SKU or product code", max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='MaterialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_type', models.CharField(blank=True, help_text='Custom type if not in dropdown', max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='material_attachments/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('attachment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='workshop_app.attachmenttype')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workshop_app.material')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['attachment_type', 'upload_date'],
            },
        ),
    ]
