# Generated by Django 4.2.20 on 2025-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0005_attachmenttype_material_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
