# Generated by Django 4.2.20 on 2025-05-02 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_app', '0006_alter_material_material_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Unique client identifier', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Company or individual name', max_length=100)),
                ('type', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='company', max_length=10)),
                ('industry', models.CharField(blank=True, help_text="Category of client's business", max_length=100)),
                ('reference_source', models.CharField(blank=True, help_text='How the client found us', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='General notes about the client')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect'), ('former', 'Former')], default='active', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('social_media', models.TextField(blank=True, help_text="Links to client's social profiles")),
                ('street_address', models.CharField(blank=True, max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID / VAT Number', max_length=50)),
                ('payment_terms', models.CharField(blank=True, help_text='Net 30, COD, etc.', max_length=50)),
                ('currency', models.CharField(blank=True, default='CHF', max_length=10)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account_status', models.CharField(blank=True, help_text='Good Standing, Credit Hold, etc.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_completed', models.IntegerField(default=0)),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('first_project_date', models.DateField(blank=True, null=True)),
                ('latest_project_date', models.DateField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workshop_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('primary_contact', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('direct_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('communication_preference', models.CharField(blank=True, help_text='Email/Phone/In-person preference', max_length=20)),
                ('working_hours', models.CharField(blank=True, max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workshop_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comm_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('meeting', 'Meeting'), ('other', 'Other')], default='email', max_length=10)),
                ('summary', models.TextField(help_text='Brief description of communication')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('client_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='workshop_app.clienthistory')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_app.contactperson')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('other', 'Other')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='client_documents/')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workshop_app.client')),
            ],
        ),
    ]
