# Generated by Django 4.2.20 on 2025-05-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0007_client_clienthistory_contactperson_communication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='client_communications/'),
        ),
    ]
