# Generated by Django 4.2.20 on 2025-05-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop_app', '0008_communication_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this machine'),
        ),
    ]
