# Generated by Django 4.2.20 on 2025-05-06 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import workshop_app.models.job


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workshop_app', '0009_machine_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#cccccc', help_text='Hex color code like #ff0000', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Order for display')),
            ],
            options={
                'verbose_name_plural': 'Job Statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='job',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workshop_app.client'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop_app.contactperson'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expected_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_general',
            field=models.BooleanField(default=False, help_text='General workshop job'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='Personal job for an operator'),
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner for personal jobs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='percent_complete',
            field=models.IntegerField(default=0, help_text='0-100'),
        ),
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/jobs/'),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='current_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_machines', to='workshop_app.job'),
        ),
        migrations.CreateModel(
            name='StaffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_since', models.DateTimeField(blank=True, null=True)),
                ('show_active_job_banner', models.BooleanField(default=True)),
                ('default_scan_for', models.CharField(choices=[('job', 'Job'), ('material', 'Material'), ('machine', 'Machine')], default='job', max_length=10)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('active_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='workshop_app.job')),
                ('personal_job', models.ForeignKey(blank=True, help_text="User's personal job", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workshop_app.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff Settings',
            },
        ),
        migrations.CreateModel(
            name='JobMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='workshop_app.job')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.CharField(blank=True, max_length=100)),
                ('result', models.CharField(choices=[('success', 'Successful'), ('scrap', 'Scrap/Waste'), ('failed', 'Failed'), ('returned', 'Returned to Inventory')], default='success', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workshop_app.job')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_usages', to='workshop_app.material')),
            ],
            options={
                'verbose_name_plural': 'Job Materials',
                'ordering': ['-date_used'],
            },
        ),
        migrations.CreateModel(
            name='JobMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('setup_time', models.IntegerField(default=0, help_text='Setup time in minutes')),
                ('operation_time', models.IntegerField(default=0, help_text='Operation time in minutes')),
                ('cleanup_time', models.IntegerField(default=0, help_text='Cleanup time in minutes')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('setup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cleanup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this usage is ongoing')),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_usages', to='workshop_app.job')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_usages', to='workshop_app.machine')),
            ],
            options={
                'verbose_name_plural': 'Job Machine Usages',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='JobLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_type', models.CharField(choices=[('design', 'Design'), ('production', 'Production'), ('assembly', 'Assembly'), ('quality_control', 'Quality Control'), ('packaging', 'Packaging'), ('other', 'Other')], max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours worked', max_digits=5)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to='workshop_app.job')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Labor Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JobFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('machine_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_status', models.CharField(choices=[('not_billed', 'Not Billed'), ('partially_billed', 'Partially Billed'), ('fully_billed', 'Fully Billed'), ('paid', 'Paid')], default='not_billed', max_length=20)),
                ('billed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('invoice_reference', models.CharField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='workshop_app.job')),
            ],
            options={
                'verbose_name_plural': 'Job Financials',
            },
        ),
        migrations.CreateModel(
            name='JobActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_type', models.CharField(choices=[('activation', 'Job Activation'), ('deactivation', 'Job Deactivation'), ('material_usage', 'Material Usage'), ('machine_usage', 'Machine Usage'), ('status_change', 'Status Change'), ('other', 'Other Activity')], max_length=20)),
                ('description', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workshop_app.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.ForeignKey(default=workshop_app.models.job.get_default_status, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='workshop_app.jobstatus'),
        ),
    ]
